dictionaries = ["en_us", "en_gb"]
ignore_paths = ["util/**/*", "Cargo.lock", "deny.toml", "LICENSE-*", "THIRD-PARTY-NOTICES.txt"]
use_global = false
words = [
  "acpy",
  "adel",
  "aload",
  "argind",
  "asort",
  "asort",
  "asorti",
  "astore",
  "beginfile",
  "bignum",
  "binmode",
  "borrowck",
  "brif",
  "bumpalo",
  "bytecount",
  "clippy",
  "compl",
  "conv",
  "convfmt",
  "cranelift",
  "ctype",
  "cygwin",
  "decpre",
  "decpst",
  "dsl",
  "endfile",
  "eprint",
  "errno",
  "fatals",
  "fflush",
  "fieldwidths",
  "fload",
  "fnr",
  "fpat",
  "fstore",
  "functab",
  "funs",
  "gawk",
  "gawk's",
  "gensub",
  "getline",
  "gsub",
  "hwm",
  "icall",
  "icase",
  "idk",
  "ignorecase",
  "imm",
  "immf",
  "incpre",
  "incpst",
  "instr",
  "instrs",
  "intrp",
  "ish",
  "jit",
  "jmp",
  "lol",
  "lshift",
  "lvalue",
  "lvalues",
  "mdel",
  "mdim",
  "miri",
  "mkbool",
  "mktime",
  "mload",
  "monomorphising",
  "monomorphization",
  "mpfr",
  "mtch",
  "neq",
  "newtype",
  "nexfile",
  "nextf",
  "nextfile",
  "nmtch",
  "nsinclude",
  "nums",
  "ofmt",
  "ofs",
  "ors",
  "patsplit",
  "pcpy",
  "prec",
  "prefetcher",
  "procinfo",
  "redir",
  "reentrant",
  "reimplementation",
  "reparsed",
  "rlength",
  "roundmode",
  "rshift",
  "rstart",
  "rvalue",
  "scpy",
  "scrutinee",
  "srand",
  "sstore",
  "stmnt",
  "stmnts",
  "strftime",
  "strnum",
  "strtonum",
  "subsep",
  "superset",
  "symtab",
  "syntaxes",
  "systime",
  "tbreak",
  "textdomain",
  "tolower",
  "toupper",
  "truthify",
  "tyl",
  "typedness",
  "tyr",
  "tys",
  "ucall",
  "ucmd",
  "unsplit",
  "uutests",
  "uutils",
  "vcall",
  "wasi",
  "wip",
]
